language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker images # print all images building
  - docker tag your-docker-reverseproxy-image-name your-dockerhub-username/your-reverseproxy-image-nam:v1
  - docker tag your-docker-udagram-user-image-name your-dockerhub-username/your-docker-udagram-user-image-name:v1
  - docker tag your-docker-udagram-feed-image-name your-dockerhub-username/your-docker-udagram-feed-image-name :v1
  - docker tag  your-docker-frontend-image-name your-dockerhub-username/your-docker-frontend-image-name:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push your-dockerhub-username/your-reverseproxy-image-nam:v1
  - docker push your-dockerhub-username/your-docker-udagram-user-image-name:v1
  - docker push your-dockerhub-username/your-docker-udagram-feed-image-name :v1
  - docker push your-dockerhub-username/your-docker-frontend-image-name:v1
