apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-name #reverseproxy for exemple
  labels:
    app: your-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-name
  template:
    metadata:
      labels:
        app: your-name
    spec:
      containers:
        - name: your-name
          image: your-dockerhub-username/your-docker-image-name:v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      restartPolicy: Always
