apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-name #backend-user for-exemple
  labels:
    app: your-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: your-name
  template:
    metadata:
      labels:
        app: your-name
    spec:
      containers:
        - name: your-name
          image: your-dockerhub-username/your-docker-image-name:v1
          envFrom:
            - secretRef:
                name: your-env-secret-name
            - secretRef:
                name: your-aws-secret-name
            - configMapRef:
                name: your-configmap-name
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 2000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
